development:
  adapter: postgresql
  encoding: utf8
  database: limiter_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: limiter_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: limiter_production
  pool: 5
  username: 
  password:
